name: 'Runs Probot Settings app'
description: 'Runs probot-settings to set up repository defaults.'
author: 'elstudio'
branding:
  icon: 'settings'
  color: 'purple'
inputs: 
  debug:
    description: 'Print script debugging info'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: 'entrypoint.sh'
  env:
    DEBUG: ${{ inputs.debug }}
 
