name: 'GitHub Action to run Probot Settings'
description: 'Runs probot-settings to set and enforce repository defaults.'
author: 'elstudio'
branding:
  icon: 'settings'
  color: 'purple'
inputs: 
  debug:
    description: 'Print script debugging info'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    DEBUG: ${{ inputs.debug }}
 
