name: Node.js CI
on:
  push:
    branches:
      - main
      - "dependabot/**"
  pull_request:
    types:
      - opened
      - synchronize
      
jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x  
    # - uses: bahmutov/npm-install@v1
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
    